version: '3.8'

services:
  backend:
    image: jithingeorge10/quick-commerce-backend:latest
    ports:
      - "5000:5000"

    env_file:
      - .env
    depends_on:
      - mongodb

  frontend:
    image: jithingeorge10/quick-commerce-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend


volumes:
  mongo-data:
