version: '3.8'

services:
  backend:
    image: jithingeorge10/quick-commerce-backend:latest
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=quickcommerce
    env_file:
      - .env
    depends_on:
      - mongodb

  frontend:
    image: jithingeorge10/quick-commerce-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongodb:
    image: mongo:5
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
